<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ExamValidate extends FormRequest {

    public function authorize(): bool {
        return true;
    }

    public function rules(): array {
        return [
            'historia_id'   => 'required',
            'examen_tipo_id' => 'required',
            'pa'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fc'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fr'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            't'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'peso'          => 'required',
            'talla'         => 'required',
            'imc'           => 'required',
            'motivo_consulta' => 'required',
            'm'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto'       => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',  
            'rc'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto'       => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto'       => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto'       => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto'       => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_pap'         => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_ivaa'        => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'mac_id'        => 'required',
            'fum'           => 'nullable|date',   
            'fpp'           => 'nullable|date',
            'edad_gestacional'      => 'nullable|string',
            'apreciacion_general'   => 'nullable|string',
            'piel_mucosas'          => 'nullable|string',
            'aparato_respiratorio'  => 'nullable|string',
            'cardio_vascular'   => 'nullable|string',
            'abdomen'           => 'nullable|string',
            'i_abm'             => 'nullable|string',
            'ap_abm'            => 'nullable|string',
            'c_abm'             => 'nullable|string',
            'p_abm'             => 'nullable|string',
            'mo_abm'            => 'nullable|string',
            'io_ro_abm'         => 'nullable|string',
            'genito_urinario'   => 'nullable|string',
            'neurologico'       => 'nullable|string',
            'au'                => 'nullable|string',
            'spp'               => 'nullable|string',
            'lcf'               => 'nullable|string',
            'du'                => 'nullable|string',
            'mf'                => 'nullable|string',
            'oh'                => 'nullable|string',
            'psc_prox_1'        => 'nullable|string',
            'psc_prox_2'        => 'nullable|string',
            'psc_prox_3'        => 'nullable|string',
            'psc_prox_4'        => 'nullable|string',
            'psc_prox_5'        => 'nullable|string',
            'psc_prox_6'        => 'nullable|string',
            'nutricion'         => 'nullable|string',
            'psicologia_1'      => 'nullable|string',
            'psicologia_2'      => 'nullable|string',
            'psicologia_3'      => 'nullable|string',
            'psicologia_4'      => 'nullable|string',
            'odontologia'       => 'nullable|string',
            'pezon'             => 'nullable|string',
            'recomendaciones'   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
        ];
    }

    public function messages(): array {
        return [
            'tipo_examen.required'      => 'El tipo de Examen es requerido',
            'pa'                        => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fc'                        => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fr'                        => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            't'                         => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'peso.required'             => 'El campo PESO es requerido',
            'talla.required'            => 'El campo TALLA es requerido',
            'imc.required'              => 'El campo IMC es requerido',
            'motivo_consulta.required'  => 'El campo MOTIVO DE CONSULTA es requerido',
            'm.regex'                   => 'El campo M tiene caracteres no válidos',
            'rc.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto.regex'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',  
            'rc.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto.regex'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto.regex'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto.regex'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rc.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'g.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'p.regex'                   => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'r1.regex'                  => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_parto.regex'             => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_pap.regex'               => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'u_ivaa.regex'              => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'mac.required'              => 'El campo MAC es requerido',
            'fum.required'              => 'El campo FUM es requerido',
            'fum.date'                  => 'nullable|date',   
            'fpp.required'              => 'El campo FPP es requerido',
            'fpp.date'                  => '',
            'edad_gestacional.string'   => '',
            'apreciacion_general.string' => '',
            'piel_mucosas.string'         => '',
            'aparato_respiratorio.string' => '',
            'cardio_vascular.string'      => '',
            'abdomen.string'              => '',
            'i_abm.string'                => '',
            'ap_abm.string'               => '',
            'c_abm.string'                => '',
            'p_abm.string'                => '',
            'mo_abm.string'               => '',
            'io_ro_abm.string'            => '',
            'genito_urinario.string'      => '',
            'neurologico.string'          => '',
            'au.string'                   => '',
            'spp.string'                  => '',
            'lcf.string'                  => '',
            'du.string'                   => '',
            'mac.string'                  => '',
            'oh.string'                   => '',
            'psc_prox_1.string'           => '',
            'psc_prox_2.string'           => '',
            'psc_prox_3.string'           => '',
            'psc_prox_4.string'           => '',
            'psc_prox_5.string'           => '',
            'psc_prox_6.string'           => '',
            'nutricion.string'            => '',
            'psicologia_1.string'         => '',
            'psicologia_2.string'         => '',
            'psicologia_3.string'         => '',
            'psicologia_4.string'         => '',
            'odontologia.string'          => '',
            'pezon.string'                => '',
            'recomendaciones.regex'       => 'El campo Recomendaciones solo puede contener letras, comas, números y espacios',
        ];
    }
}
