<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ExamValidate extends FormRequest {

    public function authorize(): bool {
        return true;
    }

    public function rules(): array {
        return [
            'historia_id'   => 'required',
            'examen_tipo_id' => 'required',
            'pa'            => 'nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fc'            => 'nullable|string',
            'fr'            => 'nullable|string',
            't'             => 'nullable|string',
            'peso'          => 'required',
            'talla'         => 'required',
            'imc'           => 'required',
            'motivo_consulta' => 'required',
            'm'             => 'nullable|string',
            'rc'            => 'nullable|string',
            'g'             => 'nullable|string',
            'p'             => 'nullable|string',
            'r1'            => 'nullable|string',
            'u_parto'       => 'nullable|string',
            'u_pap'         => 'nullable|string',
            'u_ivaa'        => 'nullable|string',
            'mac_id'        => 'required',
            'fum'           => 'nullable|date',   
            'fpp'           => 'nullable|date',
            'edad_gestacional'      => 'nullable|string',
            'apreciacion_general'   => 'nullable|string',
            'piel_mucosas'          => 'nullable|string',
            'aparato_respiratorio'  => 'nullable|string',
            'cardio_vascular'   => 'nullable|string',
            'abdomen'           => 'nullable|string',
            'genito_urinario'   => 'nullable|string',
            'd_abm'             => 'nullable|string',
            'i_abm'             => 'nullable|string',
            'ap_abm'            => 'nullable|string',
            'c_abm'             => 'nullable|string',
            'p_abm'             => 'nullable|string',
            'mo_abm'            => 'nullable|string',
            'io_ro_abm'         => 'nullable|string',
            'neurologico'       => 'nullable|string',
            'au'                => 'nullable|string',
            'spp'               => 'nullable|string',
            'lcf'               => 'nullable|string',
            'du'                => 'nullable|string',
            'mf'                => 'nullable|string',
            'oh'                => 'nullable|string',
            'psc_prox_1'        => 'nullable|string',
            'psc_prox_2'        => 'nullable|string',
            'psc_prox_3'        => 'nullable|string',
            'psc_prox_4'        => 'nullable|string',
            'psc_prox_5'        => 'nullable|string',
            'psc_prox_6'        => 'nullable|string',
            'nutricion'         => 'nullable|string',
            'psicologia_1'      => 'nullable|string',
            'psicologia_2'      => 'nullable|string',
            'psicologia_3'      => 'nullable|string',
            'psicologia_4'      => 'nullable|string',
            'odontologia'       => 'nullable|string',
            'pezon'             => 'nullable|string',
            'recomendaciones'   => 'nullable|string',
        ];
    }

    public function messages(): array {
        return [
            'tipo_examen.required'      => 'El tipo de Examen es requerido',
            'peso.required'             => 'El campo PESO es requerido',
            'talla.required'            => 'El campo TALLA es requerido',
            'imc.required'              => 'El campo IMC es requerido',
            'motivo_consulta.required'  => 'El campo MOTIVO DE CONSULTA es requerido',
            'mac.required'              => 'El campo MAC es requerido',
            'mac_id.required'           => 'MAC es requerido',
        ];
    }

    protected function prepareForValidation(): void {
        $this->merge([
            'historia_id'       => trim(strip_tags($this->historia_id)),
            'examen_tipo_id'    => trim(strip_tags($this->examen_tipo_id)),
            'pa'                => trim(strip_tags($this->pa)),
            'fc'                => trim(strip_tags($this->fc)),
            'fr'                => trim(strip_tags($this->fr)),
            't'                 => trim(strip_tags($this->t)),
            'peso'              => trim(strip_tags($this->peso)),
            'talla'             => trim(strip_tags($this->talla)),
            'imc'               => trim(strip_tags($this->imc)),
            'motivo_consulta'   => trim(strip_tags($this->motivo_consulta)),
            'm'                 => trim(strip_tags($this->m)),
            'rc'                => trim(strip_tags($this->rc)),
            'g'                 => trim(strip_tags($this->g)),
            'p'                 => trim(strip_tags($this->p)),
            'r1'                => trim(strip_tags($this->r1)),
            'u_parto'           => trim(strip_tags($this->u_parto)),
            'u_pap'             => trim(strip_tags($this->u_pap)),
            'u_ivaa'            => trim(strip_tags($this->ivaa)),
            'mac_id'            => trim(strip_tags($this->mac_id)),
            'fum'               => trim(strip_tags($this->fum)),
            'fpp'               => trim(strip_tags($this->fpp)),
            'edad_gestacional'      => trim(strip_tags($this->edad_gestacional)),
            'apreciacion_general'   => trim(strip_tags($this->apreciacion_general)),
            'piel_mucosas'          => trim(strip_tags($this->piel_mucosas)),
            'aparato_respiratorio'  => trim(strip_tags($this->aparato_respiratorio)),
            'cardio_vascular'   => trim(strip_tags($this->cardio_vascular)),
            'abdomen'           => trim(strip_tags($this->abdomen)),
            'genito_urinario'   => trim(strip_tags($this->genito_urinario)),
            'd_abm'             => trim(strip_tags($this->d_abm)),
            'i_abm'             => trim(strip_tags($this->i_abm)),
            'ap_abm'            => trim(strip_tags($this->ap_abm)),
            'c_abm'             => trim(strip_tags($this->c_abm)),
            'p_abm'             => trim(strip_tags($this->p_abm)),
            'mo_abm'            => trim(strip_tags($this->mo_abm)),
            'io_ro_abm'         => trim(strip_tags($this->io_ro_abm)),
            'neurologico'       => trim(strip_tags($this->neurologico)),
            'au'                => trim(strip_tags($this->au)),
            'spp'               => trim(strip_tags($this->spp)),
            'lcf'               => trim(strip_tags($this->lcf)),
            'du'                => trim(strip_tags($this->du)),
            'mf'                => trim(strip_tags($this->mf)),
            'oh'                => trim(strip_tags($this->oh)),
            'psc_prox_1'        => trim(strip_tags($this->psc_prox_1)),
            'psc_prox_2'        => trim(strip_tags($this->psc_prox_2)),
            'psc_prox_3'        => trim(strip_tags($this->psc_prox_3)),
            'psc_prox_4'        => trim(strip_tags($this->psc_prox_4)),
            'psc_prox_5'        => trim(strip_tags($this->psc_prox_5)),
            'psc_prox_6'        => trim(strip_tags($this->psc_prox_6)),
            'nutricion'         => trim(strip_tags($this->nutricion)),
            'psicologia_1'      => trim(strip_tags($this->psicologia_1)),
            'psicologia_2'      => trim(strip_tags($this->psicologia_2)),
            'psicologia_3'      => trim(strip_tags($this->psicologia_3)),
            'psicologia_4'      => trim(strip_tags($this->psicologia_4)),
            'odontologia'       => trim(strip_tags($this->odontologia)),
            'pezon'             => trim(strip_tags($this->pezon)),
            'recomendaciones'   => trim(strip_tags($this->recomendaciones)),
        ]);
    }
}
